name: Restart Discord Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Alle 6 Stunden
  workflow_dispatch:  # Ermöglicht manuellen Start

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Code aus dem Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js einrichten
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: npm install

      # 4. PM2 installieren
      - name: Install PM2 globally
        run: npm install -g pm2

      # 5. Discord Bot mit PM2 starten
      - name: Start Discord Bot with PM2
        run: |
          pm2 start index.js --name "discord-bot"
          pm2 save

      # 6. Zeige laufende Prozesse
      - name: Show running processes
        run: pm2 list

      # 7. PM2-Logs anzeigen (optional)
      - name: Show PM2 logs
        run: pm2 logs discord-bot
